# 监听端口（注意需要引号）
listen_addrs:
  - ":443"
  - ":80"

# 可选：启用 Socks5 前置代理
#enable_socks5: true
# 可选：配置 Socks5 代理地址
#socks_addr: 127.0.0.1:40000

# 可选：是否允许所有域名转发
#allow_all_hosts: true

# 可选：转发规则
# host是请求域名，为*则匹配所有域名，高级域名可匹配低级域名，如baidu.com，可匹配www.baidu.com
# target是转发目标，端口省略则转发端口等于请求端口，完全省略则转发给请求域名
rules:
  - host: baidu.com
    target: 111.111.111.111:443
  - host: www.github.com
    target: 123.123.123.123
  - host: www.test.com
  - host: *

#可选：目标映射
#对转发目标进行映射，解决同时支持http和https时端口不一样的映射问题
target_mapping:
  - old: "123.123.123.123:80"
    new: "123.123.123.123:8080"
  - old: "123.123.123.123:443"
    new: "123.123.123.123:8081"
